### ISSUE TITLE
Add rules for php-fpm

### ISSUE THREAD

**Issue by bryn1u** [HardenedBSD/secadm-rules#12]
Hey,

If i see correctly there is missing rule for php-fpm.

> pax {
>         path: "/usr/local/sbin/php-fpm",
>         pageexec: false,
>         mprotect: false,
>         segvguard: false,
> }

Without this rule we will get:

> [36327] pid 65369 (php-fpm), uid 0: exited on signal 11 (core dumped)

**Comment by pkubaj** [comment]
Fixed in https://github.com/HardenedBSD/secadm-rules/commit/5a2b3f58228d530f266069acaa252ba20a59e01d
